language: python

sudo: required

cache:
  directories:
  - $HOME/.ccache
  - $HOME/.cache/pip

python:
  - 3.6

env:
  global:
    AUDIODEV=null
    CC=gcc
    CXX=g++
    MYPYPATH=/tmp/typehints
    PATH=/usr/lib/ccache:$PATH

before_install:
- pip install --target /tmp/typehints --no-deps uqbar>=0.2.15
- sudo make -C .travis/ install-scsynth-deps
- sudo make -C .travis/ install-scsynth
- scsynth -v
- sudo usermod -a -G audio travis
- sudo make -C .travis/ prep-dummy-soundcard

install:
- pip install -e .
- pip install -e .[test]

before_script:
- sudo -E su $USER -c "jackd -r -ddummy -r44100 -p1024" &
- sleep 5 # give jackd time to start
- sudo -E su $USER -c "scsynth -D 0 -H dummy -R 0 -u 57110" &
- sleep 5 # give jackd time to start
- killall scsynth

script:
- make black-check
- make mypy
- sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; make sanity-check"
- sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; make pytest-travis"

notifications:
  email: false
